title: The Omegawytch Chronicles
description: Preserving the legendary 2002 RuneScape blog logs by 56Warrior.
theme: jekyll-theme-cayman

# Register the chapters collection
collections:
  chapters:
    output: true
    permalink: /chapters/:name/